### ISSUE TITLE
Extracting GPS Data

### ISSUE THREAD

**Issue by nxfxcom** [ZerBea/hcxdumptool#147]
Hello,

I love this code and use it a lot! I am also able to capture the GPS -packages. However I cant seem to figure out how to best extract them. Right now I am using the hcxpcapngtool to covert them for Hashcat but can figure out how to get the GPS data out!

Thank you

**Comment by ZerBea** [comment]
The steps to use GPS data:
Connect USB or Bluetooth GPS device to your computer.
Make sure the device got a fix. Running cat /dev/your_gps_device should show you an output of cocordinates.
`$ cat /dev/ttyACM0
`start hcxdumptool
`$ hcxdumptool -i your_interface --use_gps_device=/dev/ttyACM0 -o test.pcapng`
From now on GPS data from your GPS device are stored to every received packet from your WiFi interface.

When finished, you can convert GPS data and WiFi data running hcxpcapngtool:
`$ hcxpcapngtool -o test.22000 --nmea=gpsdata.nmea test.pcapng`

Now you can use gpsbabel (commandline or GUI) to convert the NMEA data to every other format (e.g. for GARMIN, for VIKING,... etc)
`$ gpsbabel -i nmea -f gpsdata.nmea -o gpx,gpxver=1.1 -F gpsdata.gpx`

Every GPS device that support NMEA 0183 should work with hcxdudmptool,  e.g.:
https://www.navilock.de/produkt/60169/technische_details.html?setLanguage=en

Closed this report, because it isn't an issue, but you can still ask your questions here.
