### ISSUE TITLE
What is the impact of PMKID attack on the network?

### ISSUE THREAD

**Issue by telemoondo** [ZerBea/hcxdumptool#200]
I tried running wireshark from another computer while I ran

sudo hcxdumptool -i wlan0 -o test.pcapng -t 5 --enable_status=5

I successfully captured a PMKID and was able to convert it to a hash for hashcat and crack the password. 

But my biggest question is what is the impact of running hcxdumptool? Running a deauth against a network obviously shows a bunch of deauth packets is there anything that hcxdumptool does that shows a red flag to the network?

**Comment by ZerBea** [comment]
The impact on the target depend on the options you use to disable some (or all) attack modes. By default options (nothing disabled) it is huge!
To get a PMKID you don't need to inject DEAUTHENTICATION frames (disable by: --disable_deauthentication).
To get a 4way handshake, you don't need to inject DEAUTHENTICATION frames (disable by: --disable_deauthentication).
Yo can stop the attack after some frames and restart it again (--stop_ap_attacks, resume_ap_attacks).
I recommend to disable all attack modes by setting all switches. Than remove the switches step by step and see what happens.

Help menu will give you an overview.
Closed this, because it isn't an issue, but you can still ask your questions here.
