### ISSUE TITLE
Supported adapters 

### ISSUE THREAD

**Issue by energy1984** [ZerBea/hcxdumptool#24]
Are those listed the only ones supported? What do I have these I can do something?
ualcomm Atheros AR928X Wireless Network Adapter (PCI-Express) (rev 01)
 Atheros Communications, Inc. AR9271 802.11n 1

thank you

**Comment by ZerBea** [comment]
The listed adapters are that adapters which are tested and working.
Most of the "n" adapters are not working, because of some driver issuses.
Read more here:
https://hashcat.net/forum/thread-7717-post-41509.html#pid41509
or here:
https://github.com/ZerBea/hcxdumptool/issues/12
or here:
https://hashcat.net/forum/thread-6661-post-41488.html#pid41488
