### ISSUE TITLE
Filter_ap 

### ISSUE THREAD

**Issue by hqcdestrukto** [ZerBea/hcxdumptool#248]
Hey Zerb,

Very impressive work you've accomplished. 

Quick question, i added a series of MAC addresses to a file that i tried using with rule1 (protection). However?  They still seem to get picked on. The addresses are in a plain *.txt file one on top of the other. Is the syntax right?

I've also seen your recommendation to create a BPF file. Could I create one with approximately 20 MACs? If so does the command append to the file or overwrites? Could I just enter all 20 in a single command?

**Comment by ZerBea** [comment]
Filter mode in combination with a filter list is only active in transmission branch.
The reception branch is not affected by this filters. If an AP transmit a PMKID or if a CLIENT and and AP doing a 4way handshake it is still recorded by hcxdumptool.
If only the AP is inside the filter list, a CLIENT will be still under attack and you will get a valid EAPOL M2 from it.

Running a BPF will prevent this:
$ hcxdumptool -m <interface>
$ tcpdump -i <inerface>  not wlan addr2 11:22:33:44:55:66 and not wlan addr2 11:22:33:44:55:66 and not .... -ddd > protect.bpf

The only limit known to the user space is BPF_MAXINSNS (4096). It’s the maximum number of instructions that the unprivileged BPF code can have.

Please open a discussion, because it is not a bug and this is a bug tracker.
https://github.com/ZerBea/hcxdumptool/discussions
