### ISSUE TITLE
get IP

### ISSUE THREAD

**Issue by LLH-l** [ZerBea/hcxdumptool#249]
Can  get the IP address of the network layer ?  To locate according to IP address

**Comment by ZerBea** [comment]
That is a question to be asked here:
https://github.com/ZerBea/hcxdumptool/discussions

hcxdumptool/hcxlabtool is designed to work on layer 2 only. Network stuff is layer 3 and above. 
Layer types are explained here:
https://github.com/ZerBea/hcxdumptool/discussions/244#discussioncomment-4497315

tshark or Wireshark will do the trick (e.g. filter traffic between two IP addresses):
$ tshark -r mypcap.pcap 'ip.addr==192.168.1.158 and ip.addr==64.12.24.50'

Closed, because this is a bug tracker and that is not a bug.
