### ISSUE TITLE
Stuck!

### ISSUE THREAD

**Issue by frequencyg** [ZerBea/hcxdumptool#36]
using a RT2080 usb card my attack  gets stuck to this state
https://imgur.com/a/V6qyQER Also,can someone tell me how to properly install my network drivers for this card?
Thank you!

**Comment by ALBARAA78** [comment]
Same but with intel 8260

**Comment by ZerBea** [comment]
The driver must support monitor mode and packet injection!
Most of the AC adapters doesn't support this features.

Read more here:
https://forums.kali.org/archive/index.php/t-37076.html
Hello everyone. I'm in the market for a new 'ac' chip. Currently I have this one (https://wikidevi.com/wiki/Intel_Dual_Band_Wireless-AC_8260_(8260NGW)) which seems to support monitor mode under "iwlwifi" but does not support packet injection properly.

Closed this because it is a driver issue.

**Comment by ALBARAA78** [comment]
about month ago on rtl8723ae i tested this and it was working and i was able to capture pmkid
i tested it today and it i got suck 
is it an update issue

**Comment by ZerBea** [comment]
Is the driver updated, too?
From wikidevi:
https://wikidevi.com/wiki/Rtl8723ae
Supported modes
    STA (Station) mode: supported
    IBSS (Ad-Hoc) mode: supported
    AP (Master) mode: supported
    Mesh (802.11s) mode: supported
    P2P mode: supported
    Monitor mode: supported
    Packet injection: unknown

**Comment by ZerBea** [comment]
What is the output of:
iw dev <your interface> info
