### ISSUE TITLE
orange pi zero

### ISSUE THREAD

**Issue by Virtualmemorycode** [ZerBea/hcxdumptool#399]
add gpio suport orange pi zero

**Comment by ZerBea** [comment]
That's not feasible, because I don't have an Orange Pi.

I recommend to use WiringPi Orange to get the same features:
https://github.com/OrangePiLibra/WiringPi
The examples section include a script to flash a LED:
https://github.com/OrangePiLibra/WiringPi/blob/master/examples/blink.sh

https://forum.armbian.com/topic/7067-orange-pi-pc-how-to-use-gpio-for-push-buttons-tutorial/

Modify or compile the examples and add them to your .bash_profile.
