### ISSUE TITLE
initialization hanging with rtl8192eu

### ISSUE THREAD

**Issue by respz** [ZerBea/hcxdumptool#55]
Hi. I bought another adapter with chipset rtl8192eu. I installed [mange's driver](https://github.com/Mange/rtl8192eu-linux-driver) and am able to use airodump. It works ok to capture packages. But it hangs when I use hcxdumptools.

```
# lsusb
Bus 001 Device 002: ID 2357:0108 TP-Link TL-WN822N Version 4 RTL8192EU
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```

```
# ip link set wlan0 down
# iw dev wlan0 set type monitor
# ip link set wlan0 up
# iw dev
phy#0
	Interface wlan0
		ifindex 3
		wdev 0x1
		addr 50:3e:aa:48:0b:48
		type monitor
		txpower 12.00 dBm

```

**Comment by ZerBea** [comment]
airodump-ng is a passive dumper (it receive packets), while hcxdumptool is active (send packets; packet injection). That means, you can't compare airdodump-ng (passive) with hcxdumptool (active).
The driver must(!) support packet injection, but it looks like it doesn't. And following the link you posted, I can't find any useful information that this driver supports full packet injection.
Also wikidevi doesn't have information about this driver:
https://wikidevi.com/wiki/Rtl8xxxu

Supported modes
    STA (Station) mode: supported
    IBSS (Ad-Hoc) mode: unknown
    AP (Master) mode: unknown
    Mesh (802.11s) mode: unknown
    P2P mode: unknown
    Monitor mode: unknown
    Packet injection: unknown

BTW:
Only TP-Link TL-WN822N v1/v2 support monitor mode and(!) packet injection.
There are tons of issues about v3 and higher like this here:
https://github.com/Mange/rtl8192eu-linux-driver/issues/88
and more here:
https://github.com/schollz/find-lf/issues/16
http://keep-it-sim.blogspot.com/2013/08/compatible-wireless-network-adapters.html
https://www.raymond.cc/blog/best-compatible-usb-wireless-adapter-for-backtrack-5-and-aircrack-ng/
There are also tx power issues running this driver:
https://github.com/Mange/rtl8192eu-linux-driver/issues/80

Closed, because it is a driver issue and not related to hcxdumptool.
