### ISSUE TITLE
Start NIC??

### ISSUE THREAD

**Issue by graham30rad** [ZerBea/hcxdumptool#58]
Can anyone tell me why at MAC ACCESS POINT I am seeing "(incremented on every new client)" instead of "(start NIC)" ?? Is this why I am not receiving any PMKID's?﻿ Or is it even an issue that it's different? It runs fine, no errors, I'm just not getting any pmkid's, after it running for the guts of an hour.

**Comment by ZerBea** [comment]
$ hcxdumptool -i interface --enable_status=1
initialization...
start capturing (stop with ctrl+c)
INTERFACE................: wlp3s0
ERRORMAX.................: 100 errors
FILTERLIST...............: 0 entries
MAC CLIENT...............: fcc2335cd3ae  thisMAC is used to request M1 from an ACCESS POINT inclusive PMKID (only if AP using PMKIDs. Not all AP's do this!)
MAC ACCESS POINT.........: 0005783719cd (incremented on every new client) this MAC's are used to request M2 from a CLIENT
EAPOL TIMEOUT............: 150000
REPLAYCOUNT..............: 62231
ANONCE...................: 28ae5d10e35daabd5225b8e3134064c5e0b181671fab78b1ca60e95dd29d617a
 (ANONCE to calculate PKE)
[11:22:15 - 001] 112233445566 -> fcc2335cd3ae [FOUND PMKID CLIENT-LESS]

If the AP use PMKIDs, hcxdumptool wil get them < 5 minutes.

Possible reasons, why you do not get a PMKID:
1. AP doesn't use PMKIDs
2. AP is not in RANGE
3 Your driver doesn't support monitor mode and full packet injection

To test this, run
$ hcxdumptool -i interface --do_rcascan

You should receive at least one message: AP IN RANGE.
If not, AP is out of RANGE or packet injection is not working (typically if you use an INTEL chipset).

Closed this, because it ins't an ISSUE.
But you can still ask your questions here.
