### ISSUE TITLE
is there a specific order to where we can place options in our command phrase?

### ISSUE THREAD

**Issue by careyjames** [ZerBea/hcxdumptool#67]
is there a specific order to where we can place options in our command phrase?

**Comment by ZerBea** [comment]
No, there is no specific option order for the command line.
Every option can be used once. If you double an option, the last one is used.
Also, bash variables, expansions and command substitutions are allowed:
https://www.gnu.org/software/bash/manual/html_node/Shell-Expansions.html

Exception: --enable_status
Here we use a bitmask
1: EAPOL
2: PROBEREQUEST/PROBERESPONSE
4: AUTHENTICATON
8: ASSOCIATION
16: BEACON

Example:
To get EAPOL and BEACON status, the option value is 17 (1+16)

$ export WLANDEV=wlan0
$ export

Example of a command line running bash variables:
$ export WLANDEV=`ls -1 /sys/class/net | grep ^wl`
$ export ARCHIVNAME=`date +'%Y%m%d%H%M'`
$ hcxdumptool --gpio_button=4 --gpio_statusled=17 -i $WLANDEV -o $ARCHIVNAME.pcapng --poweroff --filterlist=blacklistown --filtermode=1 --give_up_ap_attacks=100000 --give_up_deauthentications=100000 --enable_status=1

Closed this thread, because it isn't an issue related to hcxdumptool, but you can still ask questions here.

**Comment by careyjames** [comment]
thank you!
