### ISSUE TITLE
openssl evp.h error 

### ISSUE THREAD

**Issue by help789** [ZerBea/hcxdumptool#73]

**Comment by help789** [comment]
![Capture](https://user-images.githubusercontent.com/55892162/65794864-a57fe380-e186-11e9-8103-d2f6f84d9e23.PNG)

**Comment by help789** [comment]
sir what should i do

**Comment by help789** [comment]
after make command i get this error

**Comment by help789** [comment]
@ZerBea sir kindly reply sooner

**Comment by LowSkillGamer** [comment]
> sir what should i do
Try install libssl1.1 and libssl-dev

sudo apt install libssl1.1 libssl-dev

**Comment by ZerBea** [comment]
Step 1:
read README.md section requirements:
Requirements
libopenssl and openssl-dev installed

Step 2:
satisfy requirements /develop files) if they are not installed by your distributions as default. All Debian related distributions (KALI is one of them)  doesn't install develop files (-dev)!
Use the package management system of your distribution to install the dependencies.
BTW:
That and over thousands other things are the reason for me to use Arch Linux.

@LowSkillGamer thaks for your response

You canstill ask questions hrere, but I close this issue, because it is related to missing files of your distribution and not to hcxdumptool.

**Comment by ZerBea** [comment]
https://github.com/ZerBea/hcxdumptool/issues/101#issuecomment-598068155

**Comment by akshat12233** [comment]
> > sir what should i do
> 
> Try install libssl1.1 and libssl-dev
> 
> **sudo apt install libssl1.1 libssl-dev**
> 
> If already installed, use
> **sudo apt install --reinstall libssl1.1 libssl-dev**

by using the commands in my terminal i m getting error 
which is 
unable to locate pacakage libssl-dev
please help....

**Comment by strasharo** [comment]
What's the distribution you're using?

**Comment by akshat12233** [comment]
I m using Kali linux please help

**Comment by ZerBea** [comment]
The required package  is part of KALI:
https://pkg.kali.org/pkg/openssl
The recommended way to install it is this:
https://installlion.com/kali/kali/main/l/libssl-dev/install/index.html
If it doesn't work, your package management system is not updated or more likely broken and need to be updated or fixed:
https://superuser.com/questions/1410570/cant-install-anything-on-kali-linux-unable-to-locate-package

BTW:
KALI is not a distribution to be used by Linux beginners.
https://www.infoworld.com/article/3060814/should-beginners-install-kali-linux-on-their-computers.html

**Comment by akshat12233** [comment]
Thanx bro i wil switch

**Comment by ZerBea** [comment]
This will help new Linux users to pick their first distribution:
https://itsfoss.com/best-linux-beginners/

**Comment by akshat12233** [comment]
Thankyou
