### ISSUE TITLE
Multiple adapters at once

### ISSUE THREAD

**Issue by LowSkillDeveloper** [ZerBea/hcxdumptool#97]
I can connect immediately 2-3 adapters to raspberry pi. And here the question arises. Does it make sense to run hcxdumptool on multiple adapters at once. They will not interfere with each other?

And also I heard that some programs work with two adapters at once, for example, first scans ap and clients. The second sends packets. Is such an implementation possible here, and is it practical?

**Comment by ZerBea** [comment]
That depend on your tactics:

Does it make sense to run hcxdumptool on multiple adapters at once?
You can do it (run 3 x hcxdumptool) if you take care about overlapping channels:
$ hcxdumptool -i interface1 -c 1 -o test1.pcapng 
$ hcxdumptool -i interface2 -c 6 -o test2.pcapng 
$ hcxdumptool -i interface3 -c 11 -o test2.pcapng 
It doesn't makes sense if you're scanning, because the interfaces will interfere and attack each other.

And also I heard that some programs work with two adapters at once, for example, first scans ap and clients. The second sends packets. Is such an implementation possible here, and is it practical?
It is possible, but it doesn't make sense, because they will interfere. We are packet oriented and each interface must receive and transmit.
